#!/bin/bash -ex

echo ""
echo "---------------------------------------------------------"
echo "CloudFoundry Quickstart"
echo "---------------------------------------------------------"
echo ""

bundle install
vagrant init
vagrant up
